spring:
  application:
    name: auth-service-backend

  datasource:
    url: jdbc:mysql://localhost:3306/auth_service
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

jwt:
  secret: Lx0BK6OL9Z9RwPcP0FVnY/1aA3cqDSEjK8xqdPJ8Qew=
  expiration: 900000
  refresh-expiration: 604800000

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG